import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Play, TrendingUp } from "lucide-react";
import { Button } from "@/components/ui/button";
export function HeroSection() {
    const scrollToDashboard = () => {
        const element = document.getElementById("dashboard");
        if (element) {
            element.scrollIntoView({ behavior: "smooth" });
        }
    };
    return (_jsxs("section", { id: "home", className: "pt-20 min-h-screen flex items-center relative overflow-hidden", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-br from-green-700/90 to-green-800/90" }), _jsx("div", { className: "absolute inset-0 opacity-30", style: {
                    backgroundImage: "url('https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1920&h=1080')",
                    backgroundSize: "cover",
                    backgroundPosition: "center"
                } }), _jsxs("div", { className: "absolute inset-0 overflow-hidden", children: [_jsx("div", { className: "absolute top-1/4 left-1/4 w-2 h-2 bg-yellow-400/50 rounded-full animate-bounce-gentle" }), _jsx("div", { className: "absolute top-1/3 right-1/4 w-1 h-1 bg-yellow-300/40 rounded-full animate-bounce-gentle", style: { animationDelay: '0.5s' } }), _jsx("div", { className: "absolute bottom-1/3 left-1/3 w-1.5 h-1.5 bg-yellow-500/30 rounded-full animate-bounce-gentle", style: { animationDelay: '1s' } })] }), _jsx("div", { className: "relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "text-center text-white animate-fade-in", children: [_jsxs("h1", { className: "text-5xl md:text-7xl font-bold mb-6 leading-tight", children: ["Prediksi Harga", _jsx("span", { className: "block text-yellow-400", children: "Beras Indonesia" })] }), _jsx("p", { className: "text-xl md:text-2xl mb-8 text-gray-100 max-w-4xl mx-auto leading-relaxed", children: "Analisis tren harga beras dengan teknologi AI untuk mendukung ketahanan pangan nasional dan keputusan bisnis yang lebih baik" }), _jsxs("div", { className: "flex flex-col sm:flex-row gap-6 justify-center items-center", children: [_jsxs(Button, { onClick: scrollToDashboard, className: "relative group bg-gradient-to-r from-yellow-400 to-yellow-500 hover:from-yellow-500 hover:to-yellow-600 text-green-900 px-10 py-5 rounded-2xl font-bold text-lg transition-all duration-500 transform hover:scale-110 shadow-2xl hover:shadow-yellow-400/25 border-2 border-yellow-300 overflow-hidden", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-r from-yellow-300 to-yellow-400 opacity-0 group-hover:opacity-100 transition-opacity duration-500" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-r from-transparent via-white/30 to-transparent -translate-x-full group-hover:translate-x-full transition-transform duration-1000" }), _jsxs("div", { className: "relative z-10 flex items-center", children: [_jsx(TrendingUp, { className: "mr-3 h-6 w-6 group-hover:rotate-12 transition-transform duration-300" }), "Mulai Prediksi"] })] }), _jsxs(Button, { variant: "outline", className: "relative group border-2 border-white/70 hover:border-white text-white hover:text-green-900 bg-transparent hover:bg-white px-10 py-5 rounded-2xl font-bold text-lg transition-all duration-500 transform hover:scale-105 shadow-lg hover:shadow-white/20 backdrop-blur-sm overflow-hidden", children: [_jsx("div", { className: "absolute inset-0 bg-white opacity-0 group-hover:opacity-100 transition-opacity duration-500" }), _jsx("div", { className: "absolute inset-0 bg-white/20 rounded-2xl scale-0 group-hover:scale-100 transition-transform duration-700" }), _jsxs("div", { className: "relative z-10 flex items-center", children: [_jsx(Play, { className: "mr-3 h-6 w-6 group-hover:translate-x-1 transition-transform duration-300" }), "Lihat Demo"] })] })] })] }) })] }));
}
